### ISSUE TITLE
Model accuracy

### ISSUE THREAD

**Issue by jiuge-sun** [aioz-ai/MICCAI21_MMQ#2]
hello author，How much is the experimental error made in accordance with your parameters?

**Comment by Gazeal** [comment]
The experimental error is approximately 1.58%, accounting for all experiments on our hardware setup introduced in the paper. However, we figure out that some trained models may suffer up to a 3% accuracy gap because the automatically quantifying process may bias to some over-confident samples of the first trained meta-model. Hence, its effectiveness is then minimized.  Note that over-confident samples are samples with the wrong predicted labels but their confident scores are high. You can try changing the initial seed if you suffer from that problem to find a better initial meta-model.

**Comment by jiuge-sun** [comment]
Thank you very much for your reply
